### ISSUE TITLE
This hangs the compiler in lazy mode

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/drivers_flame1d#7]
This issue describes some trouble getting the flame1d case working in lazy eval mode.  The trouble is that the compiler appears to go berserk forever when compiling `eos.get_internal_energy` call from [here](https://github.com/illinois-ceesd/drivers_flame1d/blob/d8ae6396b79438d5568f30644e9faf173660865c/flame1d.py#L403) when a locally formed (and constant) mass fractions array is passed as an argument vs. when `cv.species_mass_fractions` is used. 

To reproduce the issue, install `mirgecom@y1-production` and `drivers_flame1d@lazy_test` and run the timing_run:

`python -m mpi4py ./flame1d -i timing_run_params.yaml`

Using the version of `y` from [this line](https://github.com/illinois-ceesd/drivers_flame1d/blob/d8ae6396b79438d5568f30644e9faf173660865c/flame1d.py#L392) works fine.

Here is a dump of what the relevant data is in lazy mode.  In eager mode, the case runs correctly.
```
ipdb> cv.species_mass_fractions
array([DOFArray((<pytato.array.IndexLambda object at 0x7fe96ae72580>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe97ee46f70>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe97edf2070>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe97ee1f5e0>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe97ee38640>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe981264580>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe9810e7250>,))],
      dtype=object)
ipdb> y
array([DOFArray((<pytato.array.IndexLambda object at 0x7fe96bfffdf0>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe96c0020d0>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe96c002310>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe96c002580>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe96c0027f0>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe96c002a60>,)),
       DOFArray((<pytato.array.IndexLambda object at 0x7fe96c002cd0>,))],
      dtype=object)
ipdb> y_burned
array([9.18702785e-176, 8.53517662e-020, 1.99947297e-001, 8.07802672e-037,
       8.18480439e-002, 5.43388456e-033, 7.18204659e-001])
```

@thomasgibson @inducer @kaushikcfd

**Comment by kaushikcfd** [comment]
Update: The profiler says it spends most time in `pytato.generate_loopy` -> `CombineMapper`. This was used by the v1-materializer that to check if the expression had more than 1 dependencies in order to respect `ImplStored` tags. I think the better materializer in https://github.com/inducer/pytato/pull/127 should solve this. Will try it and integrate that into `pytato-array-context-transforms` branch and see how that goes.
